language: csharp
solution: NemSharp.sln
install:
  - nuget restore NemSharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NemSharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NemSharp.Tests/bin/Release/NemSharp.Tests.dll